### ISSUE TITLE
8.0.7之后版本docker镜像无法启动报错？

### ISSUE THREAD

**Issue by kervin521** [Tencent/TencentKona-8#110]
容器启动时报错，8.0.7版本正常
```
Cannot create VM thread. Out of system resources.,Error occurred during initialization of VM

```
![lQLPJxxUKMNgndRgzQKisCSfwNVF9_0SA_9RVH4AfQA_674_96](https://user-images.githubusercontent.com/9798724/223291155-fee4b2bb-e22c-431a-a469-08eb62c65faf.png)

**Comment by shiyuexw** [comment]
麻烦提供下启动命令

**Comment by kervin521** [comment]
@shiyuexw 
```Dockerfile
ENTRYPOINT ["java","-XX:+UseContainerSupport","-XX:+UseAsyncGCLog","-XX:MaxRAMPercentage=90.0","-jar","sf-app.jar"]
```

**Comment by shiyuexw** [comment]
看起来是资源不足的问题，方便的话，提供下镜像和启动镜像的命令

**Comment by kervin521** [comment]
8.0.15 已解决，未复现

**Comment by kervin521** [comment]
我已经基于KonaJDK 8做了如下镜像：
docker push kervin521/konajdk:8.0.15_8u382-alpine
docker push kervin521/konajdk:8.0.15_8u382-jre
docker push kervin521/konajdk:8.0.15_8u382-aarch64
docker push kervin521/konajdk:8.0.15_8u382

8.0.15_8u382-alpine：基于Alpine做的，支持x86_64架构，并解决中文乱码问题，可以通过apk add xxx安装其他工具
8.0.15_8u382-jre：基于Debian制作的，支持x86_64架构，并解决中文乱码问题，可以通过apt install xxx安装其他工具
8.0.15_8u382-aarch64：基于Alpine制作的，支持aarch64架构，并解决中文乱码问题，可以通过apk add xxx安装其他工具
8.0.15_8u382：基于Ubuntu 制作的，支持x86_64架构，并解决中文乱码问题，可以通过apt instal xxx安装其他工具

x86_64架构：已经在戴尔、联想、新华三等硬件上使用，并应用于20多个现场
aarch64架构：已经在长城飞腾系列、华为鲲鹏系列等硬件上使用，即将应用2个现场

以上镜像默认安装fontconfig iputils vim sysstat htop curl方便定位问题
