### ISSUE TITLE
konajdk/konajdk:8没有字体库

### ISSUE THREAD

**Issue by yincangshiwei** [Tencent/TencentKona-8#111]
使用konajdk/konajdk:8镜像的时候，会发现缺少了字体库。如何解决这问题，里面也没有 apt-get啥的，怎么安装fontconfig

**Comment by kervin521** [comment]
@yincangshiwei 我已经基于KonaJDK 8做了如下镜像：
docker push kervin521/konajdk:8.0.15_8u382-alpine
docker push kervin521/konajdk:8.0.15_8u382-jre
docker push kervin521/konajdk:8.0.15_8u382-aarch64
docker push kervin521/konajdk:8.0.15_8u382

8.0.15_8u382-alpine：基于Alpine做的，支持x86_64架构，并解决中文乱码问题，可以通过apk add xxx安装其他工具
8.0.15_8u382-jre：基于Debian制作的，支持x86_64架构，并解决中文乱码问题，可以通过apt install xxx安装其他工具
8.0.15_8u382-aarch64：基于Alpine制作的，支持aarch64架构，并解决中文乱码问题，可以通过apk add xxx安装其他工具
8.0.15_8u382：基于Ubuntu 制作的，支持x86_64架构，并解决中文乱码问题，可以通过apt instal xxx安装其他工具

x86_64架构：已经在戴尔、联想、新华三等硬件上使用，并应用于20多个现场
aarch64架构：已经在长城飞腾系列、华为鲲鹏系列等硬件上使用，即将应用2个现场

以上镜像默认安装fontconfig iputils vim sysstat htop curl方便定位问题
