### ISSUE TITLE
8.0.10fiber版本遇到崩溃

### ISSUE THREAD

**Issue by PurXZY** [Tencent/TencentKona-8#112]
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (javaCalls.cpp:56), pid=19, tid=0x00007f7540ca5700
#  guarantee(!thread->is_Compiler_thread()) failed: cannot make java calls from the compiler
#
# JRE version: OpenJDK Runtime Environment (8.0_332-b01) (build 1.8.0_332_fiber-b1)
# Java VM: OpenJDK 64-Bit Server VM (25.332-b1 mixed mode, sharing linux-amd64 compressed oops)
# Core dump written. Default location: /cnc/run/gamesvr/core or core.19
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#

---------------  T H R E A D  ---------------

Current thread (0x00007f756886a590):  JavaThread "C1 CompilerThread1" daemon [_thread_in_vm, id=32, stack(0x00007f7540ba6000,0x00007f7540ca6000)]

Stack: [0x00007f7540ba6000,0x00007f7540ca6000],  sp=0x00007f7540ca2e30,  free space=1011k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [libjvm.so+0xb0de8a]  VMError::report_and_die()+0x1da
V  [libjvm.so+0x4ff032]  report_vm_error(char const*, int, char const*, char const*)+0x62
V  [libjvm.so+0x6a754f]  JavaCallWrapper::JavaCallWrapper(methodHandle, Handle, JavaValue*, Thread*)+0x20f
V  [libjvm.so+0x6a9164]  JavaCalls::call_helper(JavaValue*, methodHandle*, JavaCallArguments*, Thread*)+0x834
V  [libjvm.so+0x4fa7ba]  Coroutine::call_forkjoinpool_method(Thread*, Method*, JavaCallArguments*, JavaValue*)+0xfa
V  [libjvm.so+0x4fab4e]  Coroutine::try_compensate(Thread*)+0x6e
V  [libjvm.so+0x93d3a0]  ObjectMonitor::enter(Thread*)+0xb0
V  [libjvm.so+0x673520]  InstanceRefKlass::acquire_pending_list_lock(BasicLock*)+0xa0
V  [libjvm.so+0xb0f1d2]  VM_GC_Operation::doit_prologue()+0x82
V  [libjvm.so+0xb17f21]  VM_G1IncCollectionPause::doit_prologue()+0x11
V  [libjvm.so+0xb151bd]  VMThread::execute(VM_Operation*)+0x1bd
V  [libjvm.so+0x5a7116]  G1CollectedHeap::attempt_allocation_slow(unsigned long, unsigned char, unsigned int*, unsigned int*)+0x336
V  [libjvm.so+0x5a72ed]  G1CollectedHeap::allocate_new_tlab(unsigned long)+0xdd
V  [libjvm.so+0x4838a5]  CollectedHeap::allocate_from_tlab_slow(KlassHandle, Thread*, unsigned long)+0x145
V  [libjvm.so+0x66578b]  CollectedHeap::common_mem_allocate_init(KlassHandle, unsigned long, Thread*)+0x6b
V  [libjvm.so+0x652ce8]  InstanceKlass::allocate_instance(Thread*)+0x38
V  [libjvm.so+0x6b2042]  java_lang_String::basic_create(int, Thread*)+0x32
V  [libjvm.so+0x6b2400]  java_lang_String::create_from_unicode(unsigned short*, int, Thread*)+0x30
V  [libjvm.so+0xa74cfe]  StringTable::intern(Handle, unsigned short*, int, Thread*)+0x23e
V  [libjvm.so+0xa74fca]  StringTable::intern(Symbol*, Thread*)+0x5a
V  [libjvm.so+0x4ef314]  ConstantPool::string_at_impl(constantPoolHandle, int, int, Thread*)+0xe4
V  [libjvm.so+0x41989d]  ciEnv::get_constant_by_index_impl(constantPoolHandle, int, int, ciInstanceKlass*)+0x28d
V  [libjvm.so+0x419eca]  ciEnv::get_constant_by_index(constantPoolHandle, int, int, ciInstanceKlass*)+0x10a
V  [libjvm.so+0x441a55]  ciBytecodeStream::get_constant()+0x1b5
V  [libjvm.so+0x3679ee]  GraphBuilder::load_constant()+0x1e
V  [libjvm.so+0x372ef2]  GraphBuilder::iterate_bytecodes_for_block(int)+0x16f2
V  [libjvm.so+0x3739c1]  GraphBuilder::iterate_all_blocks(bool)+0x151
V  [libjvm.so+0x37660e]  GraphBuilder::GraphBuilder(Compilation*, IRScope*)+0x4fe
V  [libjvm.so+0x37ccdc]  IR::IR(Compilation*, ciMethod*, int)+0x23c
V  [libjvm.so+0x35d811]  Compilation::build_hir()+0xe1
V  [libjvm.so+0x35e005]  Compilation::compile_java_method()+0x85
V  [libjvm.so+0x35e122]  Compilation::compile_method()+0x42
V  [libjvm.so+0x35e496]  Compilation::Compilation(AbstractCompiler*, ciEnv*, ciMethod*, int, BufferBlob*)+0x266
V  [libjvm.so+0x35f030]  Compiler::compile_method(ciEnv*, ciMethod*, int)+0xd0
V  [libjvm.so+0x4ac6c6]  CompileBroker::invoke_compiler_on_method(CompileTask*)+0xcb6
V  [libjvm.so+0x4adc87]  CompileBroker::compiler_thread_loop()+0x6a7
V  [libjvm.so+0xabfe01]  JavaThread::thread_main_inner()+0xf1
V  [libjvm.so+0x960452]  java_start(Thread*)+0x132
C  [libpthread.so.0+0x7ea5]  start_thread+0xc5

**Comment by miao-zheng** [comment]
协程的下个版本修复该问题
