### ISSUE TITLE
arm版本编译教程有么，网站查的教程都不对，错误很多

### ISSUE THREAD

**Issue by cumthxy** [Tencent/TencentKona-8#14]

**Comment by daisyqhuang** [comment]
您编译的环境，参数配置，以及出现的报错能否告知呢？目前我们在aarch64机器上的编译的主要参数有：

**Comment by cumthxy** [comment]
> 您编译的环境，参数配置，以及出现的报错能否告知呢？
> 目前我们在aarch64机器上的编译并没有设置特别的参数 ，只有是否编译jfr的--enable-jfr参数的区别，但这应该不会解决编译的错误。

您好，我编译了，但是没有出现jre,目录结构如下：
`bin             classes           gen_profile_3        gensrc_no_srczip    lib
break_iterator  classes_security  gensrc               gensrc_x11wrappers  objs
btclasses       gendocsrc_rmic    gensrc_headers       impsrc              _the.CORBA.binaries.imported
btclasses_rmic  gen_profile_1     gensrc_jdwp_doc      include
btnative        gen_profile_2     gensrc_jdwp_headers  jce
`
与你们提供的x86版本的有很大差异，没有 man以及jre目录。
是我编译的不对么。
我的编译环境是 linux-aarch64，没有配置别的参数了。
使用的是dev-arrch64分支的源代码，先是运行了configure,之后make 进行的。
用的docker容器，容器采用的是 yum install 安装的jdk "1.8.0_151 。
请问我这样错的对么。
谢谢

**Comment by cumthxy** [comment]
您好，我编译了，但是没有出现jre,目录结构如下：
bin classes gen_profile_3 gensrc_no_srczip lib break_iterator classes_security gensrc gensrc_x11wrappers objs btclasses gendocsrc_rmic gensrc_headers impsrc _the.CORBA.binaries.imported btclasses_rmic gen_profile_1 gensrc_jdwp_doc include btnative gen_profile_2 gensrc_jdwp_headers jce
与你们提供的x86版本的有很大差异，没有 man以及jre目录。
是我编译的不对么。
我的编译环境是 linux-aarch64，没有配置别的参数了。
使用的是dev-arrch64分支的源代码，先是运行了configure,之后make 进行的。
用的docker容器，容器采用的是 yum install 安装的jdk "1.8.0_151 。
请问我这样错的对么。
谢谢

**Comment by daisyqhuang** [comment]
> 您好，我编译了，但是没有出现jre,目录结构如下：
> bin classes gen_profile_3 gensrc_no_srczip lib break_iterator classes_security gensrc gensrc_x11wrappers objs btclasses gendocsrc_rmic gensrc_headers impsrc _the.CORBA.binaries.imported btclasses_rmic gen_profile_1 gensrc_jdwp_doc include btnative gen_profile_2 gensrc_jdwp_headers jce
> 与你们提供的x86版本的有很大差异，没有 man以及jre目录。
> 是我编译的不对么。
> 我的编译环境是 linux-aarch64，没有配置别的参数了。
> 使用的是dev-arrch64分支的源代码，先是运行了configure,之后make 进行的。
> 用的docker容器，容器采用的是 yum install 安装的jdk "1.8.0_151 。
> 请问我这样错的对么。
> 谢谢

编译的产出物在 ${your openjdk source code dir}/build/linux-aarch64-normal-server-*/images/j2sdk-image目录下

**Comment by linzang** [comment]
> 您好，我编译了，但是没有出现jre,目录结构如下：
> bin classes gen_profile_3 gensrc_no_srczip lib break_iterator classes_security gensrc gensrc_x11wrappers objs btclasses gendocsrc_rmic gensrc_headers impsrc _the.CORBA.binaries.imported btclasses_rmic gen_profile_1 gensrc_jdwp_doc include btnative gen_profile_2 gensrc_jdwp_headers jce
> 与你们提供的x86版本的有很大差异，没有 man以及jre目录。
> 是我编译的不对么。
> 我的编译环境是 linux-aarch64，没有配置别的参数了。
> 使用的是dev-arrch64分支的源代码，先是运行了configure,之后make 进行的。
> 用的docker容器，容器采用的是 yum install 安装的jdk "1.8.0_151 。
> 请问我这样错的对么。
> 谢谢

您好， 要用./confiture之后  make image 就可以生成 ${your openjdk source code dir}/build/linux-aarch64-normal-server-*/images/j2sdk-image 目录了

**Comment by daisyqhuang** [comment]
暂时未看到新的回复，关闭issues。如果有后续问题可以重新打开
