### ISSUE TITLE
另一个dragonwell8?

### ISSUE THREAD

**Issue by yaojunWang** [Tencent/TencentKona-8#17]
能介绍下目标是什么以及和[dragonwell8](https://github.com/alibaba/dragonwell8)的区别么？为什么又要维护一个分支而不是贡献到dragonwell8呢？

**Comment by linzang** [comment]
您好， 感谢关注 TencentKona JDK.
KonaJDK主要是针对**腾讯**内外部各种业务场景进行适配和优化的openJDK下游版本，由**腾讯专家团队**维护并定期更新，保证Java业务的安全性与稳定性，同时总结我们在JDK上面的经验，积极参与并贡献给openJDK社区，与社区共建优秀的JDK生态。

**Comment by felixxfyang** [comment]
@yaojunWang 非常感谢关注和反馈。
Tencent OpenJDK团队，从最大化Java生态价值的角度出发，优先upstream通用性特性到OpenJDK主分支，这一点我们也在Kona项目描述中强调，并且会长期坚持。

目前JDK 15等版本中，腾讯已经是国内贡献最多的厂商，虽然我们没有刻意宣传，请关注：

- 国内厂商**历史首次**Notable OpenJDK贡献 https://blogs.oracle.com/java-platform-group/the-arrival-of-java-15
- 已有的社区贡献 https://bugs.openjdk.java.net/issues/?jql=labels%20%3D%20tencent-interest

Kona参考了主流厂商（比如Oracle、AWS）做法，主要考虑是部分厂商特性不是最广泛的通用需求，比如电商、大数据/机器学习。Tencent Kona是基于腾讯多样的、海量生产环境验证的JDK产品，安全、高可靠性、高性能、全面的CPU架构支持（x86、AARCH64），沉淀了大数据/机器学习、云原生领域的前沿经验。
