### ISSUE TITLE
请问如何配置Kona的开发环境？

### ISSUE THREAD

**Issue by foogao** [Tencent/TencentKona-8#18]
如题，感谢！

**Comment by linzang** [comment]
您好， 感谢关注KonaJDK
请参考这里： https://github.com/Tencent/TencentKona-8/wiki/%E5%AE%89%E8%A3%85%E8%AF%B4%E6%98%8E

**Comment by linzang** [comment]
另外， 如果您是需要build KonaJDK的环境，由于KonaJDK 8 基于openJDK 8 ， 所以可以参考openJDK的build方法。

**Comment by foogao** [comment]
@linzang 您好，感谢回复，可能我的表述不是很清楚，我是说如何配置Kona的编码环境，比如使用Eclipse、IntelliJ等集成开发环境。

**Comment by linzang** [comment]
@foogao 您好， 以IntelliJ idea为例， 只需要在project settings 中修改SDK路径指向TencentKona8目录即可：
![idea-Kona1](https://user-images.githubusercontent.com/56812395/103082328-cb5b9880-4614-11eb-83cd-e3ffb501e626.png)
![idea-Kona2](https://user-images.githubusercontent.com/56812395/103082338-d0204c80-4614-11eb-9566-9be2003a24b8.png)
