### ISSUE TITLE
docker 版本什么时间发布

### ISSUE THREAD

**Issue by ilanni2460** [Tencent/TencentKona-8#2]
docker 版本什么时间发布

**Comment by linzang** [comment]
您好， 目前docker版本还在开发测试中，欢迎持续关注TencentKona。

**Comment by kervin521** [comment]
Docker版本计划什么时候出来

**Comment by kervin521** [comment]
Docker版本：docker pull kervin521/konajdk:8.0.3_8u262

**Comment by kervin521** [comment]
Docker版本：
docker pull kervin521/konajdk:8.0.4_8u272-jre
docker pull kervin521/konajdk:8.0.4_8u272

**Comment by linzang** [comment]
感谢支持， 目前官方版本已经发布，可参考[安装说明](https://github.com/Tencent/TencentKona-8/wiki/%E5%AE%89%E8%A3%85%E8%AF%B4%E6%98%8E) 

示例： `docker pull ccr.ccs.tencentyun.com/konajdk_repo/tencentkona_8`

**Comment by linzang** [comment]
> Docker版本：
> docker pull kervin521/konajdk:8.0.4_8u272-jre
> docker pull kervin521/konajdk:8.0.4_8u272

非常感谢您的支持与关注 ！

**Comment by kervin521** [comment]
Docker版本：
docker pull kervin521/konajdk:8.0.5_8u282
docker pull kervin521/konajdk:8.0.5_8u282-jre
docker pull kervin521/konajdk:8.0.5_8u282-alpine
