### ISSUE TITLE
[suggest] Submit to sdkman

### ISSUE THREAD

**Issue by tonycody** [Tencent/TencentKona-8#20]
It is recommended to submit to SDKMan like other JDK releases for easy download and use.

Submission method
https://sdkman.io/vendors

SDKMan already includes the following JDKs:
AdoptOpenJDK
Amazon
Azul Zulu
BellSoft
GraalVM
TravaOpenJDK
OpenJDK

Looking forward to JDK from China.
In addition, it is recommended to submit to the IDEA JDK list so that development tools can be downloaded from China JDK

**Comment by shiyuexw** [comment]
Excuse me for late response, we will evaluate and feedback ASAP. Thanks a lot for your kind suggestion.

**Comment by tonycody** [comment]
> Excuse me for late response, we will evaluate and feedback ASAP. Thanks a lot for your kind suggestion.

Alibaba has submitted, Huawei Bi Sheng has submitted...

**Comment by shiyuexw** [comment]
已与SDKMAN的开发者进行了沟通，并提交了新的GitHub PR，代码待合入。

**Comment by johnshajiang** [comment]
@tonycody 
虽然已经多次提醒，但SDKMAN的开发者直到最近才合并了我们的PR @_@
无论怎样，现在SDKMAN已经支持了Kona JDK ;-)

```
% sdk list java | grep kona
Tencent       |     | 17.0.7       | kona    |            | 17.0.7-kona
              |     | 11.0.19      | kona    |            | 11.0.19-kona
              |     | 8.0.372      | kona    |            | 8.0.372-kona
```

**Comment by tonycody** [comment]
> @tonycody 虽然已经多次提醒，但SDKMAN的开发者直到最近才合并了我们的PR @_@ 无论怎样，现在SDKMAN已经支持了Kona JDK ;-)
> 
> ```
> % sdk list java | grep kona
> Tencent       |     | 17.0.7       | kona    |            | 17.0.7-kona
>               |     | 11.0.19      | kona    |            | 11.0.19-kona
>               |     | 8.0.372      | kona    |            | 8.0.372-kona
> ```

https://slack.sdkman.io/
加入一下官方的 Slack 应该会好交流些！

**Comment by tonycody** [comment]
> @tonycody 虽然已经多次提醒，但SDKMAN的开发者直到最近才合并了我们的PR @_@ 无论怎样，现在SDKMAN已经支持了Kona JDK ;-)
> 
> ```
> % sdk list java | grep kona
> Tencent       |     | 17.0.7       | kona    |            | 17.0.7-kona
>               |     | 11.0.19      | kona    |            | 11.0.19-kona
>               |     | 8.0.372      | kona    |            | 8.0.372-kona
> ```

还是有点问题的，现在仅仅是 sdk command 能查阅到 Tencent Kona，但官网上的JDK清单还是没有。上次阿里也是这样！
https://sdkman.io/jdks

**Comment by johnshajiang** [comment]
> https://slack.sdkman.io/
> 加入一下官方的 Slack 应该会好交流些！

已加入。

> 还是有点问题的，现在仅仅是 sdk command 能查阅到 Tencent Kona，但官网上的JDK清单还是没有。上次阿里也是这样！
https://sdkman.io/jdks

非常感谢指出这个问题。
我将会与SDKMAN的开发者沟通一下。
