### ISSUE TITLE
请问支持MacOS M1 ?

### ISSUE THREAD

**Issue by XinyueZ** [Tencent/TencentKona-8#24]

**Comment by linzang** [comment]
您好， 
感谢关注TencentKona！
Tencent Kona JDK 发布的原则是每一个版本都需要经过严格的测试，同时在腾讯内部供用户验证使用后，再提供给外部客户，所以每个平台的支持都会比较慎重。目前多平台的发布已经在计划中，相信很快就会出现在我们发布列表中。

**Comment by shiyuexw** [comment]
已提供Mac M1发行版本

**Comment by huishi-hs** [comment]
已经支持M1，关闭issue
