### ISSUE TITLE
为啥不是直接贡献到openJDK去，而是搞个独立的git？

### ISSUE THREAD

**Issue by zhengbin78** [Tencent/TencentKona-8#3]
Tencent应该可以申请加入openJDK组织，直接提供贡献，偶尔有差异化对方不接受的，再采取补丁形式提供。

**Comment by linzang** [comment]
您好， 欢迎关注kona， 之后会有一些贡献到openJDK中。 但是考虑到有些feature我们开发测试稳定之后， 到真正提交到openJDK社区，通过社区评审之后进入openJDK中，可能会需要很长的时间和流程，所以我们会对稳定的feature，先通过开源的形式放到github上，让大家能够优先使用到一些feature带来的便利。

**Comment by netroby** [comment]
牛逼，从jdk mail list过来围观的

**Comment by daisyqhuang** [comment]
暂时未看到新的回复，关闭issues。如果有后续问题可以重新打开
