### ISSUE TITLE
how to support headless mode?

### ISSUE THREAD

**Issue by baikeh** [Tencent/TencentKona-8#4]
`-Djava.awt.headless=true` not work

**Comment by IamYangxf** [comment]
Hi Baikeh, thanks for your feedback. Could you provide the detail reproduce steps, environments, configuration and symptom? 
Kona team has verified with Oracle official guide on headless mode, see https://www.oracle.com/technical-resources/articles/javase/headless.html. But it passed.
Thank you very much!

**Comment by linzang** [comment]
Dear @baikeh, 
     would you like to share your reproducer? so that we can check what is the problem. 
     Thanks!
BRs,
Lin

**Comment by linzang** [comment]
I will close this issue since there is no update.
