### ISSUE TITLE
KonaFiber

### ISSUE THREAD

**Issue by plevart** [Tencent/TencentKona-8#40]
Hi,

I see there is a branch called `KonaFiber` that includes a backport of Loom API. How stable is it at this point? Is something similar planned for `TencentKona-11` too?

**Comment by huishi-hs** [comment]
@plevart 

Konafiber's quality is verified in Tencent productions: RPC, game server, springcloud push serverice, etc. Current Konafiber code is stablized at early 2021.  In later this month, synchronized VirtualThread API with lastest loom will be published. (current API is based on Loom 202009).

Konafiber has not update Java network/IO class library for virtual thread, our internal users are suggested to use 3rd party async network/IO libs like netty.

Porting to kona11 is under developping, biggest effort is making VirtualThread works with ZGC.

We would appreicate for any feedback/comments/questions!

**Comment by huishi-hs** [comment]
No followup discussion close.
