### ISSUE TITLE
Where is the JDK 11 ? Kona-11?

### ISSUE THREAD

**Issue by cnmade** [Tencent/TencentKona-8#5]
Where is the JDK 11 ? Kona-11?
Would you please share us the develop repository?

**Comment by linzang** [comment]
we are working on JDK 11 open sourcing. so please stay tuned.

**Comment by linzang** [comment]
https://github.com/Tencent/TencentKona-11
KonaJDK 11 已经开源。 感谢支持！

**Comment by jiqing112** [comment]
> https://github.com/Tencent/TencentKona-11
> KonaJDK 11 已经开源。 感谢支持！

提一点过分的伸手要求，release的打包可以多编译几个系统的嘛，可以用github action自动化得发布编译。现在只有linux，加上windows受众会多出来很多。

有windows之后我给加到 [www.injdk.cn](www.injdk.cn) 的分发上

**Comment by shiyuexw** [comment]
Tencent Kona JDK 发布的原则是每一个版本都需要经过严格的测试，同时在腾讯内部供用户验证使用后，再提供给外部客户，所以每个平台的支持都会比较慎重。目前多平台的发布已经在计划中，相信很快就会出现在我们发布列表中。

**Comment by shiyuexw** [comment]
> > https://github.com/Tencent/TencentKona-11
> > KonaJDK 11 已经开源。 感谢支持！
> 
> 提一点过分的伸手要求，release的打包可以多编译几个系统的嘛，可以用github action自动化得发布编译。现在只有linux，加上windows受众会多出来很多。
> 
> 有windows之后我给加到 [www.injdk.cn](www.injdk.cn) 的分发上

Tencent Kona JDK 发布的原则是每一个版本都需要经过严格的测试，同时在腾讯内部供用户验证使用后，再提供给外部客户，所以每个平台的支持都会比较慎重。目前多平台的发布已经在计划中，相信很快就会出现在我们发布列表中。
