### ISSUE TITLE
国产化大需求下为什么不及时更新 arm 版的 Kona JDK？

### ISSUE THREAD

**Issue by JunlongLiang** [Tencent/TencentKona-8#51]

**Comment by shiyuexw** [comment]
Aarch64在OpenJDK292正式支持，为确保提供稳定可靠的版本，需要一定时间进行灰度测试，预计在下一次版本发布时，提供Aarch64的版本。

**Comment by shiyuexw** [comment]
aarch64 的 302 版本已经正式发布 https://github.com/Tencent/TencentKona-8/releases
