### ISSUE TITLE
“Remove the TencentSMProvider from JDK”?

### ISSUE THREAD

**Issue by metercai** [Tencent/TencentKona-8#64]
why? ...

**Comment by johnshajiang** [comment]
This provider is already refactored and in a separated jar now.
We can release the provider in a more flexible way. It won't be constrained by the quarterly release cadence of KonaJDK.
And especially this separated provider can be used to not only KonaJDK 8, but also other JDK releases, say KonaJDK 11.

The refreshed provider will be open-sourced in the feature.

**Comment by shiyuexw** [comment]
腾讯国密套件：https://github.com/Tencent/TencentKonaSMSuite

**Comment by shiyuexw** [comment]
国密已开源，关闭该issue

**Comment by shiyuexw** [comment]
关闭该issue
