### ISSUE TITLE
KonaFiber怎么进行开发

### ISSUE THREAD

**Issue by linuke** [Tencent/TencentKona-8#66]
使用linux系统进行开发的人毕竟是少数，大多数还是使用mac和window；这个你们内部开发是怎么解决的。是不是可以先出个beta或者preview版本方便进行开发。

**Comment by huishi-hs** [comment]
这个在这个月会有win、mac（x64）的版本；欢迎使用和提意见。
你们准备用在什么场景？

**Comment by linuke** [comment]
我们网关目前服务分组，每个分组对应一个线程池；目前线程数太多
