### ISSUE TITLE
KonaJDK-8.0.8-u312在容器中有性能问题？

### ISSUE THREAD

**Issue by kervin521** [Tencent/TencentKona-8#68]
![image](https://user-images.githubusercontent.com/9798724/145373004-7089429f-483e-4a55-84be-53af8502fae2.png)

如上图针对同一Java后端基于KonaJDK-8.0.7-u302做镜像在容器集群中内存、CPU正常，基于KonaJDK-8.0.8-u312做镜像在容器集群中内存100%，CPU也占用比较高

**Comment by huishi-hs** [comment]
非常感谢反馈！能否给一个可以复现和调试的用例？有一个能直接跑的docker就更好了
1. 测试环境
2. 运行的demo

**Comment by huishi-hs** [comment]
或者可以做一些对比的async profile，gc日志都会有帮助

**Comment by shiyuexw** [comment]
可以加上-XX:+UseContainerSupport ，看是否还有问题。

**Comment by kervin521** [comment]
8.0.15版本已经解决

**Comment by kervin521** [comment]
我已经基于KonaJDK 8做了如下镜像：
docker push kervin521/konajdk:8.0.15_8u382-alpine
docker push kervin521/konajdk:8.0.15_8u382-jre
docker push kervin521/konajdk:8.0.15_8u382-aarch64
docker push kervin521/konajdk:8.0.15_8u382

8.0.15_8u382-alpine：基于Alpine做的，支持x86_64架构，并解决中文乱码问题，可以通过apk add xxx安装其他工具
8.0.15_8u382-jre：基于Debian制作的，支持x86_64架构，并解决中文乱码问题，可以通过apt install xxx安装其他工具
8.0.15_8u382-aarch64：基于Alpine制作的，支持aarch64架构，并解决中文乱码问题，可以通过apk add xxx安装其他工具
8.0.15_8u382：基于Ubuntu 制作的，支持x86_64架构，并解决中文乱码问题，可以通过apt instal xxx安装其他工具

x86_64架构：已经在戴尔、联想、新华三等硬件上使用，并应用于20多个现场
aarch64架构：已经在长城飞腾系列、华为鲲鹏系列等硬件上使用，即将应用2个现场

以上镜像默认安装fontconfig iputils vim sysstat htop curl方便定位问题
