### ISSUE TITLE
StringIndexOutOfBoundsException with empty input in sun.tools.jar.Manifest.isManifestName("")

### ISSUE THREAD

**Issue by suoyi123wang** [Tencent/TencentKona-8#69]
单元测试用例如下：
![image](https://user-images.githubusercontent.com/44200574/146882880-bdcdcea4-f7e6-4bc6-8a07-c4c5659c6175.png)
源码：
![image](https://user-images.githubusercontent.com/44200574/146882970-22556dc5-11fc-4cec-b892-75eccd1a9141.png)
在调用charAt(0)之前应该先判断长度，或者直接用`name.startsWith("-")` 代替也可避免这种异常发生

**Comment by shiyuexw** [comment]
建议在调用接口前做判断。
如果觉得在isManifestName中加上判断更必要的话，建议向上游社区提PR。

**Comment by shiyuexw** [comment]
没有进一步的需求，关闭该issue
