### ISSUE TITLE
konaJDK 8 有针对国产环境arm架构下ForceSafepoint的优化？

### ISSUE THREAD

**Issue by 393042549** [Tencent/TencentKona-8#75]
今日读到一篇文章，链接：https://mp.weixin.qq.com/s/6C8tb_MW68bUF4xI0XB3cA
其中提到
![image](https://user-images.githubusercontent.com/11642518/158716502-777aa0bb-0e36-47f8-a37e-aa85d2912f2b.png)

![image](https://user-images.githubusercontent.com/11642518/158714593-1ef3a510-580e-47a5-8eb9-182c241dadc4.png)

但文章中并未提及具体详细原因，所以请问：
1.是否存在对arm环境下频繁发生ForceSafepoint的优化
2.具体是什么原因产生的频繁ForceSafepoint，以及如何优化？

ps:文章中提到的臧琳同学，是不是你？ @linzang

**Comment by linzang** [comment]
你好，
啊 被翻牌子了T_T, 确实是我。 
首先非常感谢关注Kona。
这里简单解释下，当时用户使用的是闭源版本的JDK（非Kona）， 我们只能用现有的现象和数据推测具体原因。 从观察的到现象，该业务场景下该JDK存在大量ForceSavepoint，我们推测该JDK在应该是针对某些其他场景做了定制化。 但由于没有源代码，这里看不到具体逻辑。 

所以回答下这两个问题：
> 1.是否存在对arm环境下频繁发生ForceSafepoint的优化
从现象看，闭源JDK似乎在这里有些额外变动， 但KonaJDK这里与OpenJDK相同，我们所有的改动都会经过社区，不敢乱动~。
> 2.具体是什么原因产生的频繁ForceSafepoint，以及如何优化？
由于没有源代码，我们也没法深入分析。 从Kona的代码来看，这里不应该存在大量的ForceSafepoint。事实验证也确实如此。

谢谢！
Lin

**Comment by 393042549** [comment]
你好，臧同学
感谢你的回复。

之所以会认为Kona JDK可能存在ForceSafepoint相关优化，是因为文章中描述：
1.使用带debug信息的Kona JDK（一个临时验证版本？），仍然会存在问题，只是复现周期变长。
2.替换成Release版本的Kona JDK，问题始终没有复现。
![image](https://user-images.githubusercontent.com/11642518/159388496-6fb6b262-542c-4a42-9b19-96c82daeb5c8.png)

另外，所谓的闭源版本JDK，有没有可能是Oracle版本的JDK？

**Comment by 393042549** [comment]
好的，谢谢

准备先换成较新版本的openjdk试下。
不行再换成Kona JDK试下。
再不行，就只能跑路了。

**Comment by linzang** [comment]
> 好的，谢谢
> 
> 准备先换成较新版本的openjdk试下。 不行再换成Kona JDK试下。 再不行，就只能跑路了。

可以先试试Kona ;-)

**Comment by 393042549** [comment]
更新下：
从oracle jdk 1.8.0_251版本 替换为 openjdk 1.8.0_292后，ForceSavepoint明显减少
替换前，运行4-5天后性能严重下降，重启后正常
替换后，已运行10天，目前正常，暂未复现上述问题

虽然暂未使用Kona jdk来验证，应该与open jdk一样不会复现。

运行环境：

> cpu：aarch64，huawei kunpeng 920  

> os：CentOS Linux release 7.8.2003 (AltArch)

**Comment by linzang** [comment]
感谢评测！那我就把这个issue 先关啦？

**Comment by Nachtflug** [comment]
大哥们，我们这也出现了，arm + oracle jdk 231， 火焰图一打88%时间在干安全点，有线索吗

**Comment by Nachtflug** [comment]
看到了， openjdk 8u292一次提交集成修、优化了arm下122个问题，甚至新开了目录放aarch64单独实现，说明前面的arm版本可能都是凑合用的程度，升上去就行了
