### ISSUE TITLE
Should update the supported platforms in README

### ISSUE THREAD

**Issue by johnshajiang** [Tencent/TencentKona-8#90]
The README contains the below line,
```
Tencent Kona currently supports Linux/x86_64 platform only.
```
However, Kona 8 already releases builds for Windows and Mac platforms.
https://github.com/Tencent/TencentKona-8/releases

**Comment by shiyuexw** [comment]
README已修改，感谢提醒

**Comment by cxk1998** [comment]
https://github.com/Tencent/TencentKona-8/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98
FAQ里的支持列表也改一下吧

**Comment by shiyuexw** [comment]
谢谢提醒已更新

**Comment by shiyuexw** [comment]
已修改，关闭该issue
