### ISSUE TITLE
does the coroutine support ObjectMonitor?

### ISSUE THREAD

**Issue by Clownsw** [Tencent/TencentKona-8#96]
does the coroutine support ObjectMonitor?

**Comment by miao-zheng** [comment]
We already supported ObjectMonitor, you can see the detail on this article: https://mp.weixin.qq.com/s/RZzcCUc9iM_hOLaAoqw8tg

**Comment by felixxfyang** [comment]
Close this issue since ObjectMonitor has been addressed. Please feel free to contact us if necessary
