### ISSUE TITLE
是否支持 native方法 调度

### ISSUE THREAD

**Issue by Clownsw** [Tencent/TencentKona-8#98]
native方法阻塞了, 是否会被调度？

**Comment by miao-zheng** [comment]
不知道我是否正确理解了该问题。

如果一个线程调用了native方法被阻塞，那么它不会被操作系统调度，操作系统只会调度Runnable状态的线程。
如果一个协程调用了native方法被阻塞，那么该协程会同时阻塞它的carrier thread，看起来协程已经被调度了（因为协程在carrier thread上执行），但它的carrier thread不会有机会被os调度。

**Comment by Clownsw** [comment]
> carrier thread

你好, 我想问的是当一个native方法阻塞在一个协程, 也就是阻塞了carrier thread, 那么KonaFiber是否支持将当前协程挂起并执行其他协程

**Comment by miao-zheng** [comment]
如果是协程执行native操作被阻塞，carrier thread也会被阻塞，当前carrier thread不能切换到另一个协程执行。

**Comment by Clownsw** [comment]
> carrier thread

麻烦请问有计划实现这个吗, 或者说可以通过其他方式解决？

**Comment by Clownsw** [comment]
> 如果是协程执行native操作被阻塞，carrier thread也会被阻塞，当前carrier thread不能切换到另一个协程执行。


carrier thread

麻烦请问有计划实现这个吗, 或者说可以通过其他方式解决？

**Comment by miao-zheng** [comment]
native block，本质上是linux层面的事情，java runtime没办法感知。目前java社区的官方协程Loom也不支持。

如果有一些native block操作，首先要看这些操作的频率，如果只是少量操作，不影响系统稳定性或性能，那么完全可以不改。

如果native block操作很频繁，影响性能，或者说极端情况下导致所有carrier thread卡住，常规做法是将这些操作涉及的线程放到另一个线程池中执行，不要影响协程的执行就可以。

**Comment by Clownsw** [comment]
> 感谢您的回答,

好的, 感谢您的回答

**Comment by Clownsw** [comment]
> native block，本质上是linux层面的事情，java runtime没办法感知。目前java社区的官方协程Loom也不支持。
> 
> 如果有一些native block操作，首先要看这些操作的频率，如果只是少量操作，不影响系统稳定性或性能，那么完全可以不改。
> 
> 如果native block操作很频繁，影响性能，或者说极端情况下导致所有carrier thread卡住，常规做法是将这些操作涉及的线程放到另一个独立的线程池中执行，不要影响协程的执行就可以。

好的, 感谢您的回答
