### ISSUE TITLE
请问 OWST 相关 commit 或 patch 有吗？

### ISSUE THREAD

**Issue by dibingfa** [Tencent/TencentKona-8#99]
GC线程调度优化 Optimized Work Stealing Threads
开启方式：默认开启，在启动参数里面显示添加 -XX:-UseOWSTTaskTerminator关闭
原理：GC并行线程通过Work Stealing进行负载均衡，减少GC停顿时间。原有Work Stealing算法中所有空闲GC线程都会频繁尝试work stealing造成CPU资源浪费，新算法采用一个master线程监控是否进行work stealing并在适当时机唤醒其它空闲GC线程，极大减少CPU资源浪费和进程间的CPU资源竞争。OWST在OpenJDK社区版本12以后支持，大数据Hibench测试有最多30%的性能提升，平均提升8%。

请问这个功能相关 commit 或 patch 可以定位下不？想学习下。

**Comment by shiyuexw** [comment]
可以参看 https://github.com/Tencent/TencentKona-8/commits/8.0.6-GA 下的commit代码

**Comment by sunym1993** [comment]
是否有关键字呀提示下呗，这里搜了下 OWST 没搜到

**Comment by shiyuexw** [comment]
8204947: Port ShenandoahTaskTerminator to mainline and make it default
以及相关commit

**Comment by shiyuexw** [comment]
没有进一步需求，关闭该issue
